apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apptest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sawogus29/gitops-test.git'
    targetRevision: HEAD
    path: 'charts/my-application'
    helm:
      valueFiles:
      - /values/common/values-common.yaml
      - /values/one/values-one.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'apptest'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true