apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/sawogus29/gitops-test.git'
        revision: HEAD
        directories:
          - path: values/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/sawogus29/gitops-test.git'
        targetRevision: HEAD
        path: 'charts/my-application'
        helm:
          valueFiles:
            - '/values/common/values-common.yaml'
            - '/values/{{path.basename}}/values-{{path.basename}}.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true